### ISSUE TITLE
Test failure 

### ISSUE THREAD

**Issue by frispete** [stefanofontanelli/ColanderAlchemy#96]
In an attempt to package this project for openSUSE, I stumbled upon this:
```
[   12s] ======================================================================
[   12s] ERROR: test_validator_typedecorator_override (tests.test_schema.TestsSQLAlchemySchemaNode)
[   12s] ----------------------------------------------------------------------
[   12s] Traceback (most recent call last):
[   12s]   File "/home/abuild/rpmbuild/BUILD/ColanderAlchemy-0.3.3/tests/test_schema.py", line 1255, in test_validator_typedecorator_override
[   12s]     class House(Base):
[   12s]   File "/home/abuild/rpmbuild/BUILD/ColanderAlchemy-0.3.3/tests/test_schema.py", line 1258, in House
[   12s]     door = Column(LocationEnum(['back', 'front']))
[   12s]   File "/usr/lib64/python3.4/site-packages/sqlalchemy/sql/type_api.py", line 786, in __init__
[   12s]     self.impl = to_instance(self.__class__.impl, *args, **kwargs)
[   12s]   File "/usr/lib64/python3.4/site-packages/sqlalchemy/sql/type_api.py", line 1261, in to_instance
[   12s]     return typeobj(*arg, **kw)
[   12s]   File "/usr/lib64/python3.4/site-packages/sqlalchemy/sql/sqltypes.py", line 1228, in __init__
[   12s]     self._setup_for_values(values, objects, kw)
[   12s]   File "/usr/lib64/python3.4/site-packages/sqlalchemy/sql/sqltypes.py", line 1271, in _setup_for_values
[   12s]     zip(objects, values)
[   12s] TypeError: unhashable type: 'list'
[   12s] 
[   12s] ----------------------------------------------------------------------
[   12s] Ran 45 tests in 0.080s
[   12s] 
[   12s] FAILED (errors=1)
[   12s] Test failed: <unittest.runner.TextTestResult run=45 errors=1 failures=0>
[   12s] error: Test failed: <unittest.runner.TextTestResult run=45 errors=1 failures=0>
[   12s] error: Bad exit status from /var/tmp/rpm-tmp.NcLpmq (%check)
[   12s] 
```

Any idea, what's wrong here?

**Comment by tisdall** [comment]
This seemed to be the issue I fixed with commit b45fe35f2936a5ccb705e9344075191e550af6c9 .  I didn't push a new version into PyPi because the bug was with the test case and not the actual library.  Did you need a new version pushed to PyPi to do this packaging?

**Comment by frispete** [comment]
I must have been beaten with blindness (well, working in too many areas at the same time...), so I missed this one. Using this patch right now. All is fine...

Sorry for bothering you.

**Comment by tisdall** [comment]
No problem!  I'm glad it was a simple issue.
